dependencies:
  agent_lib: /home/qyh/projects/GarFL/classtracer/target/classtracer-1.0.jar
  D4J_exec: /home/qyh/DATASET/defects4j-2.0.1/framework/bin/defects4j
  GB_exec: /home/qyh/DATASET/GrowingBugRepository/framework/bin/defects4j
models:
  summary:
    series: openai
    model: gpt-3.5-turbo-16k
    api_key: null
    base_url: https://api.kksj.org/v1
    max_tokens: 4000
    rate_limit: 6000
    cache_name: gpt-3.5-turbo-16k
  embed:
    series: jina
    model: jina-embeddings-v2-base-en
    api_key: null
    batch_size: 1024
    base_url: null
    cache_name: jina-embeddings-v2-base-en_gpt-3.5-turbo-16k
  reason:
    series: openai
    model: gpt-3.5-turbo-16k
    api_key: null
    base_url: https://api.kksj.org/v1
    max_tokens: 4000
    rate_limit: 6000
    cache_name: gpt-3.5-turbo-16k
  rerank:
    series: cohere
    model: rerank-english-v3.0
    api_key: null
    base_url: null
hyper:
  max_diagnose_rounds: 5
  sbfl_formula: ochiai
  retrieve_top_n: 50
  rerank_top_n: 50
  chat_rerank_top_n: 10
  max_module_size: 15
  min_module_size: 5
use_chat_rerank: false
use_context: true
use_context_retrieval: true
use_description_retrieval: true
clear: true
